### ISSUE TITLE
Any recent change that is causing false formatting issues?

### ISSUE THREAD

**Issue by juliohm** [domluna/JuliaFormatter.jl#910]
This code exists in the repository for a while, but the JuliaFormatter.jl started to complain about in the last days:

https://github.com/JuliaEarth/GeoStatsFunctions.jl/pull/59

Could this be caused by the latest release from 4 days ago?

**Comment by willow-ahrens** [comment]
I also noticed my CI failing recently over a change to JuliaFormatter in https://github.com/finch-tensor/Finch.jl/commit/216ec6994620cb2ccd8509c536bd9a27fe0541c0

**Comment by domluna** [comment]
#909 is probably the cause. fixed in #913

**Comment by juliohm** [comment]
Apparently the issue is still present. Got another incorrect PR suggestion today: https://github.com/JuliaEarth/GeoStatsFunctions.jl/pull/60/files

**Comment by willow-ahrens** [comment]
Could we add a few (large) repos to CI as downstream tests to check whether to formatter makes changes?

**Comment by domluna** [comment]
> Could we add a few (large) repos to CI as downstream tests to check whether JuliaFormatter has changed version-to-version?

sure. I'd be open to adding there are a few already in the test/ directory.

Turns out doing a complete rewrite and not having issues pop up if pretty difficult.

**Comment by juliohm** [comment]
Still getting false alarms with the latest release:

https://github.com/JuliaEarth/CoordRefSystems.jl/pull/256

**Comment by juliohm** [comment]
What is the plan regarding this issue? The false alarms are becoming super annoying.

**Comment by domluna** [comment]
@v1 should do it since you want the latest version of v1

**Comment by juliohm** [comment]
What about the other question? Is this a bug?

Em qui., 24 de abr. de 2025, 21:02, Dominique Luna ***@***.***>
escreveu:

**Comment by juliohm** [comment]
I am going through all my packages and fixing the version of JuliaFormatter.jl in the FormatPR.yml action:

```julia
Pkg.add(name="JuliaFormatter", version="1")
```
